"""
Plot BLUE & NIST scores as a function of sentnec length
for centroid exps on metis & presemt-dev data for en-de & de-en

Scores were generated by running scratch/centroid.py
"""

from pylab import *

from tg.mteval import parse_segment_scores

n = 0
figure(figsize=(9, 14))

for data_set in "metis", "presemt-dev":
    for lang_pair in "de-en", "en-de":
        scores_fname = "centroid/_centroid_{}_{}/centroid_{}_{}.scores".format(
            data_set, lang_pair, data_set, lang_pair)
        scores = parse_segment_scores(scores_fname)
        for measure in "BLEU", "NIST":
            n += 1
            ax = subplot(4, 2, n)
            
            r = np.corrcoef(scores["words"], scores[measure])[1,0]
            title('{}_{}\n(n={}, r={:.4f})\n'.format(data_set, 
                                                 lang_pair, 
                                                 scores.shape[0],
                                                 r))            
            xlabel("#words")
            ylabel(measure)
            
            xmax = 20 if data_set == "metis" else 50
            xlim(0, xmax)
                
            ymax = 0.5 if measure == "BLEU" else 10.0
            ylim(0.0, ymax)
            
            gca().set_aspect(xmax/ymax)
            scatter(scores["words"], scores[measure])

subplots_adjust(wspace=0.0, hspace=0.5)
savefig("_score_by_length.pdf")
savefig("_score_by_length.png")
        
            
show()        